
model_name: test_gpt2
reader:
  sources:
    - name: test
      source: rsc/data/AiHub-Largeai_SFT_QA.jsonl
      split:
        type: train
      limit: 50
      reader: read_simple
    # - name: test2
    #   source: rsc/data/single_lines.jsonl
    #   split:
    #     type: train
    #   limit: 100
    #   reader: read_simple


dataset:
  prompt: Llama31
  dataset: BaseDataset

dataloader:
  shuffle: false
  num_workers: 0 # num_workers > 0이면 메모리 더 나감
  batch_size: 1
tokenizer:
  from_pretrained: openai-community/gpt2

model:
  base_config: openai-community/gpt2
  device: cpu


loss_config:
  name: CrossEntropyLoss
  ignore_index: -100

optimizer_config:
  name: AdamW
  lr: 5e-5
  weight_decay: 0.01

scheduler_config:
  name: WarmupLinearSchedule
  warmup_steps: 100
  t_total: 1000

trainer_config:
  num_train_epochs: 1
  gradient_accumulation_steps: 4