
model_name: test_gpt2
reader:
  sources:
    - name: test
      source: rsc/data/AiHub-Largeai_SFT_QA.jsonl
      split:
        type: train
      limit: 50
      reader: read_simple



dataset:
  prompt: Llama31
  dataset: 
    name: SFTDataset
    max_length: 1024

dataloader:
  shuffle: true
  num_workers: 0 # num_workers > 0이면 메모리 더 나감
  batch_size: 1
tokenizer:
  path: openai-community/gpt2

model:
  path: openai-community/gpt2
  device: cpu


loss:
  name: CrossEntropyLoss
  ignore_index: -100

optimizer:
  name: AdamW
  lr: 5e-5
  weight_decay: 0.01

scheduler:
  name: WarmupLinearSchedule
  warmup_steps: 100
  t_total: 1000

training_arguments:
  num_train_epochs: 1
  gradient_accumulation_steps: 4