pretrained_model: test_gpt2_dpo

reader:
  sources:
    - name: test
      source: rsc/data/single_lines.jsonl
      split:
        type: test
      reader: read_simple
  

dataset:
  prompt: Llama31
  dataset: 
    name: InferenceDataset
    max_length: 924

dataloader:
  shuffle: false
  num_workers: 0 # num_workers > 0이면 메모리 더 나감
  batch_size: 8

generation_config:
  max_new_tokens: 100